OPTIONS (DIRECT=FALSE) LOAD DATA CHARACTERSET AL32UTF8
INFILE '/sample/data/Sample1.ctl'
INTO TABLE SampleTable1 TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
   Fld0 CHAR(15),
   Fld1 CHAR(100),
   Fld2,
   Fld3 DATE 'DD-MON-YY'
)
